[db.conn1]
    connName="conn1"
    engine="mysql"
    host="localhost"
    port="3336"
    user="root"
    password="secret"
    dbname="homestead"

[db.local]
    connName="local"
    engine="sqlite"
    host=""
    port=""
    user=""
    password=""
    dbname="my_db"